apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sink
  labels:
    app: sink
    name: sink
spec:
  selector:
    matchLabels:
      app: sink
  replicas: 2
  template:
    metadata:
      labels:
        app: sink
        name: sink
    spec:
      containers:
        - name: sink
          image: node:0.3
          imagePullPolicy: Never
          ports:
            - name: flask
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: flask
          readinessProbe:
            httpGet:
              path: /healthz
              port: flask
