apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle
  labels:
    app: middle
    name: middle
spec:
  selector:
    matchLabels:
      app: middle
  replicas: 1
  template:
    metadata:
      labels:
        app: middle
        name: middle
    spec:
      containers:
        - name: middle
          image: node:0.3
          imagePullPolicy: Never
          env:
            - name: CHAOS_TEST_NEXT_NODE
              value: http://sink
          ports:
            - name: flask
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: flask
          readinessProbe:
            httpGet:
              path: /healthz
              port: flask
